spring.application.name: quartz-service
server.port: 40010
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:4000/eureka/

  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/?useUnicode=true&characterEncoding=utf8
    username: test
    password: test
    driver-class-name: com.mysql.jdbc.Driver
