version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es/data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    container_name: elasticsearch2
    links:
    - elasticsearch:elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es/data2:/usr/share/elasticsearch/data

  logstash-collector:
    image: docker.elastic.co/logstash/logstash:6.1.1
    links:
    - redis:redis
    volumes:
    - ./data/logstash/logstash-collector.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 6000:6000

  logstash-indexer:
    image: docker.elastic.co/logstash/logstash:6.1.1
    links:
    - redis:redis
    - elasticsearch:elasticsearch
    volumes:
    - ./data/logstash/logstash-indexer.conf:/usr/share/logstash/pipeline/logstash.conf

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    # volumes:
    #   - ./data/kibana: /usr/share/kibana/config
    ports:
      - 5601:5601
    links:
    - elasticsearch:elasticsearch

  redis:
      image: redis:3.2-alpine


#/etc/sysctl.conf
#vm.max_map_count=262144
#sysctl -w vm.max_map_count=262144