spring.application.name: zipkin-server
server.port: 9411

zipkin.storage:
  StorageComponent: elasticsearch
  type: elasticsearch
  #type: mem

  elasticsearch:
    cluster: es-cluster
    hosts: 172.23.111.14:9200
    max-requests: 64
    index: zipkin
    index-shards: 5
    index-replicas: 1
spring:
  zipkin:
    enabled: false