spring.application.name: compute-service
server.port: 40010
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:4000/eureka/

  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

spring:
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411
    enabled: true
