spring.application.name: config-server
server.port: 5000
# git管理配置
spring.cloud.config.server.git:
  #本地git仓库
  uri: file:///d:/data/config-repo
  #远端git仓库
  #uri: git@github.com:tiny-lk/Study.git
  #searchPaths: 09.SpringCloudDemo/config-repo
