cn.chinaunicom:
  blog:
    name: 程序猿
    title: Spring Boot教程
    desc: ${cn.chinaunicom.blog.name}正在努力写《${cn.chinaunicom.blog.title}》
    # 随机字符串
    value: ${random.value}
    # 随机int
    number: ${random.int}
    # 随机long
    bignumber: ${random.long}
    # 10以内的随机数
    test1: ${random.int(10)}
    # 10-20的随机数
    test2: ${random.int[10,20]}

# 多环境配置文件激活属性
spring.profiles.active: dev