spring.application.name: api-gateway
server.port: 7000

zuul.routes:
  srv1:
    path: /s1/**
    serviceId: srv1
  srv2:
    path: /s2/**
    serviceId: srv2
  # routes to url
  s1-url:
    path: /s1-url/**
    url: http://localhost:40011/

eureka.client.serviceUrl.defaultZone: http://localhost:4000/eureka/