version: '2'
services:
  registry:
    image: registry:2
    container_name: registry_mirror
    restart: always
    volumes:
      - /opt/registry/data:/var/lib/registry
      - /opt/registry/config.yml:/etc/docker/registry/config.yml
    ports:
      - 5000:5000
