spring.application.name: compute-service
server.port: 40010
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:4000/eureka/

  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

spring:
    redis:
        host: 172.23.105.210
        password: 123456
        database: 13
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0
        port: 6379
        timeout: 0
